name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history to be able to determine version number

    - name: Install build dependencies
      run: sudo apt-get install -y libusb-1.0-0-dev libsystemd-dev libev-dev libfmt-dev libinih-dev

    - name: Bootstrap
      run: sh bootstrap.sh

    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Test install
      run: sudo make install

  debian:

    strategy:
      matrix:
        release: [stable, oldstable, testing]
    runs-on: ubuntu-latest
    container: debian:${{ matrix.release }}-slim

    steps:
    - name: Install git
      run: apt-get update && apt-get install -y git

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history to be able to determine version number

    - name: Merge into debian branch
      run: git config --system --add safe.directory "$GITHUB_WORKSPACE" && git checkout debian && git merge --no-commit "$GITHUB_REF"

    - name: Build and install
      run: install-debian.sh
